info.onCountdownEnd(function () {
    game.over(true)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    enemy1.follow(mySprite, 0)
})
controller.B.onEvent(ControllerButtonEvent.Released, function () {
    enemy1.follow(mySprite, 115)
    controller.moveSprite(mySprite, 110, 110)
    info.startCountdown(180)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    statusbar.value = statusbar.value - 3
    if (statusbar.value <= 0) {
        game.over(false)
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    enemy1.follow(mySprite, 150)
})
let statusbar: StatusBarSprite = null
let enemy1: Sprite = null
let mySprite: Sprite = null
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
enemy1 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
tiles.setTilemap(tilemap`レベル1`)
controller.moveSprite(mySprite, 120, 120)
scene.cameraFollowSprite(mySprite)
mySprite.setPosition(0, 0)
enemy1.setPosition(50, 50)
enemy1.follow(mySprite, 115)
statusbar = statusbars.create(20, 4, StatusBarKind.Health)
statusbar.positionDirection(CollisionDirection.Bottom)
info.startCountdown(100)
